### ISSUE TITLE
Missing implementation for ISO

### ISSUE THREAD

**Issue by M4iku** [CBidis/CSharp8583#5]
I am trying to add an ASCII (ISOXXXXXXXXX) but I don't have a Tag for it, how can I solve this problem?

**Comment by crypticspawn** [comment]
If you need a new Field, you can use CustomField, and then add the tags for it.

`public class CustomField140 : CustomField {
  [Tag(position: 0, tagName: "00", define the rest of the tag here)]
  public virtual string Tag00 { get; set; } 
}
`
